server.port=8080
app.name=Task Manager (DEV)
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=5963
spring.jpa.hibernate.ddl-auto=update
